version: '3.8'
services:
  backend:
    build: ./backend
    command: python ./webapp/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"